# Generated by Django 3.0.8 on 2020-07-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystorage', '0003_auto_20200719_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='image',
            new_name='myfile',
        ),
    ]
